### ISSUE TITLE
[Page Add][Enhanced function]Getting Started Page for ODYSSEY- STM32MP135D

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#446]
# This assignment has been successfully achieved 🎉

Thanks Casey and the wiki page is: https://wiki.seeedstudio.com/ODYSSEY-STM32MP135D/

## Overview
- We need your help to add the getting started page for [ODYSSEY- STM32MP135D](https://www.seeedstudio.com/Odyssey-MP135D-eMMC-p-5728.html).
- We need to connect the board with [Grove Base Hat for Raspberry Pi](https://www.seeedstudio.com/Grove-Base-Hat-for-Raspberry-Pi.html) and apply some functional modules.
## What we are trying to present:
1. Product Overview
2. Part List
3. Hardware Overview
4. Getting Started(Software / OS installation)
5. Connect with Grove - gear motor, Grove - Hall Sensor, Grove - speaker, Grove buzzer or other Grove to come up with some demos.
reference: 
[ODYSSEY – STM32MP157C](https://wiki.seeedstudio.com/ODYSSEY-STM32MP157C)
[STM21MP1 Package](https://wiki.stmicroelectronics.cn/stm32mpu/wiki/STM32MP1_Distribution_Package)
## How do we work together?
- **Leave a comment with your GitHub name below** as you accept this assignment and will complete the contents about what we are trying to present.
- The maintainer will assign and record you as our only contact for this assignment.
- You can first [Deploy this Wiki Platform Locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/) (The entire source code .zip file is only 30 M)
- You will be invited as our **"Contributor"** once you ["Pull Request"](https://wiki.seeedstudio.com/Contribution-Guide/).
- The maintainer will review the PR and then merge.
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
- For any question, the contributor can directly commend here.
### I think I can complete the assignment, but I need more time?
- The timeframe here is based on our old experience, from people who has done it or something like that.
- However, **many projects will take much more time** under actual circumstances (including the main language of the contributors receiving the task and the actual creative difficulty)
- You can leave the time you need and a brief reason, we will evaluate the situation accordingly.

**Comment by IcingTomato** [comment]
Icingtomato is working on it

**Comment by MatthewJeffson** [comment]
Hi, it is good to have you onboard:D

**Comment by IcingTomato** [comment]
I think this dev board is the best board I have been used.

**Comment by IcingTomato** [comment]
https://github.com/Seeed-Studio/stm32mp1-manifest

**Comment by MatthewJeffson** [comment]
Glad to hear that :D

> I think this dev board is the best board I have been used.

**Comment by xogium** [comment]
Any news on this?

I bought the board and so far I haven't seen any trace of usable softwares, no yocto, no buildroot, no documentation. I had to make my own ATF, optee, u-boot and kernel ports due to issues with the ones provided by Seeed.

It's a damn good thing I am familiar with ST based products, or I would have put the board in its box and not touched it again.

Not criticising, just really confused. Why does Seeed claims yocto and buildroot support yet doesn't provide it? And what happened to the person making the basic doc?

**Comment by MatthewJeffson** [comment]
Hi! @xogium I'm sorry you have to experience the board without the docs support. The person who accepted the assignment at the first place is no longer doing it.

> I had to make my own ATF, optee, u-boot and kernel ports due to issues with the ones provided by Seeed.

May I ask, if it is possible... Would you mind to help us with this development board?

I have updated the details and raise the level of the assignment. We are still looking for the person who have the ability to do this.
Best Regards,
Matthew

**Comment by xogium** [comment]
Hi @MatthewJeffson,
I'd definitely like to work on making this happen. I have previous and current experience with ST hardware and would like to offer my contributions to the wiki.

However there's a few issues that I can see, the major one being that as far as I'm aware, Seeed did NOT make any OS for this board. No buildroot nor yocto port was ever created, despite being advertised.

So my question at the moment is, are we also meant to create the buildroot/yocto configurations?

If so, I can do the buildroot one. In fact, I was planning on upstreaming the board into mainline buildroot, using my own software forks of tf-a, optee, u-boot and the linux kernel since the Seeed ones are problematic and one version behind what ST has to offer.

What should we do, considering this?

**Comment by MatthewJeffson** [comment]
Hi @xogium I'm so grateful that you can do this assignment and yes building the buildroot one will be even more perfect.:D
Do you need other support from me? 
Best Regards,
Matthew

**Comment by xogium** [comment]
Hello!
I don't think I'll need more of your help, at least not at this very moment. I should be good enough to figure out how to do this.

The only thing I want to let you know is that I will be able to do the first part of the guide for booting a basic buildroot image after building and so on, but the part with the grove sensors and such will be a bit delayed for two reasons.

* a friend wishes to buy the parts for me since I'm short on money which is nice
* but, I wish to buy a second odyssey at the same time for another project of mine, and they're currently out of stock.

We would have liked to pay in one go for everything. Do you know, when the odyssey mp135d with eMMC will be restocked so that we can get a second board, along with the grove shield and a couple of sensors to connect?

**Comment by MatthewJeffson** [comment]
Hi! @xogium It is very nice of you.
I will ask around try to get you one with the eMMC.
May I have your email so we can discuss more details?
Best Regards,
Matthew

**Comment by xogium** [comment]
Of course. I've just sent you an email on your gmail address, so that I don't have to show it publically.

**Comment by xogium** [comment]
Hi!

This is to report that I've put together a basic guide for now. It consists of the hardware description + features, intended usage, etc. and a basic getting started with buildroot guide. There is no images at all on the page, as I am not aware if Seeed offers a 3d model of the board like they do with the stm32mp157c. This is only plain text right now.

I have a couple question however.
* Should I make the pull request now so we get a basic documentation at least available on the wiki?
* Or, should I wait until I come up with the documentation on how to use grove on this platform?
* Which files should I modify, if any, besides my newly created markdown file?

It is available [here](https://github.com/xogium/seeed-wiki-documents/blob/a3e0ee4bd1c2adfea1b07bb6a8f107fbe959d131/docs/Edge/ODYSSEY/ODYSSEY_STM32MP135D/ODYSSEY%20STM32MP135D.md) if you want to take a look.

**Comment by xogium** [comment]
Hi!
Here is an updated link to the latest commit in my branch. There were a few changes made since:
* mentioned buildroot required dependencies
* fixed typo
* added an example of using gnu screen to use the serial console
* added a link to a MAC address generator
* changed link to schematics for an image of the board with hilighted serial pins

New link is [this one](https://github.com/xogium/seeed-wiki-documents/blob/07b106a13259ba08a240fd26b0aeea29af66ddb3/docs/Edge/ODYSSEY/ODYSSEY_STM32MP135D/ODYSSEY%20STM32MP135D.md)

**Comment by MatthewJeffson** [comment]
Hi @xogium Casey!
I'm so thankful that you are doing this project.
Great work!
Matthew
