### ISSUE TITLE
[Page Add][Enhanced Function] Test MicroPython programming with XIAO ESP32S3

### ISSUE THREAD

**Issue by MatthewJeffson** [Seeed-Studio/wiki-documents#515]
# This assignment has been successfully achieved 🎉

Thanks Hendra and the wiki page is: https://wiki.seeedstudio.com/XIAO_ESP32S3_Micropython/

## Overview
- We have a firmware built by one of contributor and it is designed for XIAO ESP32S3 board. 
- We are looking for someone might be able to test it:

reference: [XIAO ESP32S3 Micropython.zip](https://github.com/Seeed-Studio/wiki-documents/files/12375085/XIAO.ESP32S3.Micropython.zip)

## Assignment acceptance
- Please check the "assignee" section before accepting to see if this has already been accepted.
- Please ensure that the **requested timeline** aligns with your workflow.
- Leave your **Github Name** below to indicate that you are willing to accept the job.
- If you are taking on the assignment **for the first time**, you may receive an invitation in your GitHub mail.
## Requirements(check list)
- Prove of video presentation
- Detailed operation procedure written in **Markdown file** with [wiki standards](https://files.seeedstudio.com/wiki/wiki-ranger/Standards_of_Product_ApplicationWiki_Upload.pdf)
- Upload wiki markdown file to GitHub repository with [guide & instructions](https://wiki.seeedstudio.com/Contribution-Guide/)
- List of products used
- Code files that complete the program
## What do we offer?
We want to express our gratitude to our contributors by offering a range of rewards.  Depending on the difficulties(Tier 0/1/2/3), the time we expect(Days 1/3/7/15),  the actual  submission time and the actual submission contents, we will offer different levels of rewards.
1. We will provide our products or cash bonus to our contributors as a token of appreciation.
2. For those contributors who join our "Ranger Program"(announced soon), we offer even more exciting rewards, including access to our prototype products.
3. In addition, all contributors and their contributions will be acknowledged and showcased on our wiki platform.
## FAQ
For the ranger who accepts this assignment can have a conversation with your transition AE below

**Comment by chalei** [comment]
Hello matthew Hendra here. I think I can do this one. I already Familiar with micropython. What kind of test programming are needed for this?

**Comment by MatthewJeffson** [comment]
Hi, @chalei Hendra. Welcome onboard! We have a contributor building a firmware designed for XIAO ESP32S3 board. And we are looking for someone might be able to test it:


[XIAO ESP32S3 Micropython.zip](https://github.com/Seeed-Studio/wiki-documents/files/12375085/XIAO.ESP32S3.Micropython.zip)

there are some files on it, regarding wifi, streaming client, streaming server. If all tests fine, writing us a [wiki](https://wiki.seeedstudio.com/Name_your_website/) will be fine.

**Comment by chalei** [comment]
Hello matthew I have successfully test out the micropython firmware for the xiao ESP32S3.


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/e85b9a0d-ea56-4727-b42a-84c6f5c597c4)


since I am using windows 10 I do most of the testing using windows OS.
**1. Flashing the firmware**
for this part I am gonna be using esptool on my cmd terminal.
first I am erasing the flash memory on the Xiao Esp32S3


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/ddfc233a-4c67-4a6d-93cf-417fbc5b7742)


then I am opening the esp32_flash file using notepad++


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/448b7db8-e2fb-49ac-b1c2-845d22f2efaf)

I paste the content to my cmd and edit it like the picture below


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/b868aaa6-8c02-4cc3-ba15-273b8ff37817)

**2. Upload the example code**
For this part I am using thonny IDE
first I configure the port


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/8d95315f-e930-4db0-99df-511cfdfa50b8)

then on the view menu I check mark the file option


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/bd744eea-a197-4452-9b2e-4d8059bf4670)

Navigate to the folder where I extract example code then upload the files by right clicking on the file and choose the option like the picture below


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/b01f52d6-fe8c-4d91-a3e3-551af9b706e2)


after all the example code uploaded to xiao esp32s3 board, i change the wifi credential on both the streamin_server.py file and the Wifi.py file


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/32a8193a-c3e2-4de8-b131-a1909833eda4)


**3. Testing the streaming example**
 Before testing the streaming make sure to install the opencv python library using pip


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/e8f66bea-85fd-446f-80da-2b93726607a5)

after the opencv python library installed successfully I go back to thonny and run the streamin_server.py and copy the IP address of the xiao ESP32S3 board


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/49eb16a7-8e85-4243-a012-ecf453f64e5a)

then I go back to the extracted zip folder and open the steamin_client.py using IDLE and change the IP address part to be the same with the xiao ESP32S3 board


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/6679c5d8-df59-40d0-94d0-078082eeec0e)

and the I try to run the file and voila the streaming run successfully


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/e508804c-06d0-446b-9eba-48cb30c4d1d0)

**4. Bugs**
although I run the sample code successfully I've bumped into a few bugs when testing it

If I do a soft reboot and relaunch the code. The camera is not initialized successfully and can't reconnect to the wifi


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/f9cb6074-0f2d-4368-a596-ae402e3fb98f)

to remedy this I unplugged the board and plug it back then rerun the code

Sometimes the client side wont receive the stream due this error


![Image](https://github.com/Seeed-Studio/wiki-documents/assets/5271515/762206d3-ccc5-4b49-9291-5d4cb8dab421)


one other thing is when the streaming is running the Xiao ESP32S3 gets quite hot

**Comment by MatthewJeffson** [comment]
Thank you for providing such detailed information to us! It is great to see you doing this!

**Comment by chalei** [comment]
Hello Matthew I already make the wiki for this, please let me know if its missing something #569

**Comment by MatthewJeffson** [comment]
Hi @chalei I have seen it and will check it as soon as possible.

**Comment by chalei** [comment]
Hello @MatthewJeffson thank you for the merge

**Comment by iainwhiteigs** [comment]
I can't get the UART to work (pins 7 & 8) - has anyone tested it works?

**Comment by Harrison-Xu** [comment]
Hello, during test I got an error. 

On the client (computer) side: 
<img width="894" alt="企业微信截图_1e33e0c3-da76-419a-a0dd-3229cfea9bf4" src="https://github.com/user-attachments/assets/8772d6a6-2fb4-4c33-be72-30721a091e8e" />

On the server (XIAO) side: 
<img width="1072" alt="企业微信截图_1eca4df4-8550-4a05-b444-86086304d966" src="https://github.com/user-attachments/assets/bfdadb0d-0c17-4b4c-b5c4-f1303dda33b9" />

Could anyone help me with solving this `TCP send error object with buffer protocol required` error? Many thanks in advance!

**Comment by MatthewJeffson** [comment]
This firmware might be obsolete. The new wiki is here: https://wiki.seeedstudio.com/xiao_esp32s3_with_micropython/

**Comment by jisv48** [comment]
Hello Matthew,  I'm trying to use the "firmware." created for the esp32-sense camera and wifi by Hendra and Sharitumin. The solution is great since it will use opencv to capture video from the esp32-sense. I got a couple questions, after I flash the firmware and bring up Thonny the repl indicates; "Could not query builtin modules. Code completion may not work properly". Nevertheless the WiFi and streaming_server loads and waits for the connection from the client. When I ran the streaming_client there is not display and I get a message in the server side indicating "TCP send error object with buffer protocol required".  How can I get this to work correctly.  I have seen your response that there another firmware is availbe here: https://wiki.seeedstudio.com/xiao_esp32s3_with_micropython but it does not include the Camera module.  How can I get a resolution or what can I provided you to help to get it done.   Thanks
