### ISSUE TITLE
Xiao ESP32S3 PSRAM configuration not clear

### ISSUE THREAD

**Issue by Ilidur** [Seeed-Studio/wiki-documents#719]
**Is your feature request related to a problem? Please describe.**
I'm trying to run the esp-dl which uses an example in its tutorial that requires PSRAM. The PSRAM is not compatible with the default configuration of menuconfig. Reading the error and searching I found [this issue](https://github.com/espressif/esp-idf/issues/6288) which has the suggestion of setting PSRAM to Octal. I could not confirm from the Xiao ESP32S3 documentation what this setting should be, however the example worked after changing to Octal.

**Describe the solution you'd like**
Integrate the information of the PSRAM needing to be configured to Octal in the documentation or at least mention it in the Getting Started page in any of the 3 locations where PSRAM is also mentioned.

**Describe alternatives you've considered**
Other examples provided by Seeed using PSRAM could mention Octal such that when searching for PSRAM the setting is found easily.

**Additional context**
No additional context. Thank you for taking time to read this issue.

**Comment by MatthewJeffson** [comment]
Hi! @Ilidur Thank you for sharing your ideas with us!
We encourage our users friends to PR the contents regarding the ideas to us and that's why we launch the [Contributor Program](https://github.com/orgs/Seeed-Studio/projects/6) here. Hence would you mind change/add the contents about PSRAM usage in the wiki platform? That would be huge helpful:)
Here you can [deploy the wiki platform locally](https://wiki.seeedstudio.com/Deploy_Page_Locally/)
Then you can change the contents and PR to us with the [Pull Request Guide](https://wiki.seeedstudio.com/Contribution-Guide/)
