### ISSUE TITLE
SerialUSB is not declared in this scope - Xiao ADC/DAC example

### ISSUE THREAD

**Issue by Andy2No** [Seeed-Studio/wiki-documents#777]
In the Xiao wiki, under "Analog Input and Output" at https://wiki.seeedstudio.com/Seeeduino-XIAO/#analog-input-and-output , the example code does not compile.  It seems this has been copied from somewhere else, without checking that it works.

There are two references to SerialUSB but that is not declared.  They should both be Serial instead.

**Comment by dzalf** [comment]
+1 on this

@Andy2No is absolutely right. Facing EXACTLY the same issue:

Using `Serial`:

![image](https://github.com/Seeed-Studio/wiki-documents/assets/3759916/1c800764-e4cb-4b3a-941b-9c8087381a26)

while with `SerialUSB`:

![image](https://github.com/Seeed-Studio/wiki-documents/assets/3759916/649c6559-123e-4d17-a1f3-a106c2f4e29e)

Something is clearly _broken_ and must be fixed since all of the online references indicate to use `SerialUSB`.

Moreover, in my case, the device ONLY works with the Arduino IDE serial monitor. If I use others, for instance [YAT](https://sourceforge.net/projects/y-a-terminal/) NOTHING happens (however, that could be an issue with YAT which I highly doubt. I use YAT on a daily basis with other boards - e.g. Teensy, SAM boards -  without any issues). I am still investigating this

**Comment by MatthewJeffson** [comment]
Hi! Thanks for the report! We will check it soon!:D
Matthew

**Comment by limengdu** [comment]
```cpp
#define DAC_PIN A0 // Make code a bit more legible

float x = 0; // Value to take the sin of
float increment = 0.02;  // Value to increment x by each time
int frequency = 440; // Frequency of sine wave

void setup() 
{
  analogWriteResolution(10); // Set analog out resolution to max, 10-bits
  analogReadResolution(12); // Set analog input resolution to max, 12-bits

  Serial.begin(9600);
}

void loop() 
{
  // Generate a voltage value between 0 and 1023. 
  // Let's scale a sin wave between those values:
  // Offset by 511.5, then multiply sin by 511.5.
  int dacVoltage = (int)(511.5 + 511.5 * sin(x));
  x += increment; // Increase value of x

  // Generate a voltage between 0 and 3.3V.
  // 0= 0V, 1023=3.3V, 512=1.65V, etc.
  analogWrite(DAC_PIN, dacVoltage);

  // Now read A1 (connected to A0), and convert that
  // 12-bit ADC value to a voltage between 0 and 3.3.
  float voltage = analogRead(A1) * 3.3 / 4096.0;
  Serial.println(voltage); // Print the voltage.
  delay(1); // Delay 1ms
}
```
